runtime: php55
api_version: 1

handlers:
- url: /.*
  script: main.py
  
- url: /
  script: index.html
  secure: always
  
- url: /index\.html
  script: index.html
  secure: always
  
- url: /ten-mien\.html
  script: ten-mien.html
  secure: always
  
- url: /cloud-hosting\.html
  script: cloud-hosting.html
  secure: always
  
- url: /cloud-server\.html
  script: cloud-server.html
  secure: always

- url: /ban-quyen-windows-client\.html
  script: ban-quyen-windows-client.html
  secure: always
  
- url: /ban-quyen-windows-server\.html
  script: ban-quyen-windows-server.html
  secure: always
  
- url: /ban-quyen-office365\.html
  script: ban-quyen-office365.html
  secure: always

- url: /lien-he\.html
  script: lien-he.html
  secure: always
  
- url: /huong-dan-dang-ky\.html
  script: huong-dan-dang-ky.html
  secure: always
  
- url: /quy-dinh-su-dung\.html
  script: quy-dinh-su-dung.html
  secure: always
  
- url: /.*
  script: Error.html
  secure: always
